### ISSUE TITLE
Orders From Users and Guest - [BUG]

### ISSUE THREAD

**Issue by Haywayaheadshot** [Oniocha/Qargo-Ecommerce#17]
### [Bug Description]
- Due to the refactoring of createAuthOrder and createGuestOrder to a redux action and reducer, the algorithm can no longer tell when the user is a guest or one with credentials.

### [SUGGESTED SOLUTION]
- Successfully implementing this logic goes in hand with successfully close [this](https://github.com/Oniocha/Qargo-Ecommerce/issues/16) ticket.

**Comment by DavidQuartz** [comment]
Closed as it is related to another closed issue
